// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(craftnet_uniffiFFI)
import craftnet_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_craftnet_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_craftnet_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Main VPN client interface
 */
public protocol CraftNetVpnProtocol : AnyObject {
    
    /**
     * Connect to the VPN network
     */
    func connect() throws 
    
    /**
     * Disconnect from the VPN network
     */
    func disconnect() throws 
    
    /**
     * Get available credits
     */
    func getCredits()  -> UInt64
    
    /**
     * Get current privacy level
     */
    func getPrivacyLevel()  -> PrivacyLevel
    
    /**
     * Get current connection state
     */
    func getState()  -> ConnectionState
    
    /**
     * Get network statistics
     */
    func getStats()  -> NetworkStats
    
    /**
     * Get current VPN status
     */
    func getStatus()  -> VpnStatus
    
    /**
     * Check if connected
     */
    func isConnected()  -> Bool
    
    /**
     * Set available credits (for testing without payment)
     */
    func setCredits(credits: UInt64) 
    
    /**
     * Set privacy level
     */
    func setPrivacyLevel(level: PrivacyLevel) 
    
    /**
     * Process a packet through the tunnel (for Network Extension)
     *
     * This takes raw IP packet data, tunnels it through the VPN,
     * and returns the response packet data.
     */
    func tunnelPacket(packet: Data) throws  -> Data
    
}

/**
 * Main VPN client interface
 */
open class CraftNetVpn:
    CraftNetVpnProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_craftnet_uniffi_fn_clone_craftnetvpn(self.pointer, $0) }
    }
    /**
     * Create a new VPN client instance
     */
public convenience init(config: VpnConfig)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeCraftNetError.lift) {
    uniffi_craftnet_uniffi_fn_constructor_craftnetvpn_new(
        FfiConverterTypeVpnConfig.lower(config),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_craftnet_uniffi_fn_free_craftnetvpn(pointer, $0) }
    }

    

    
    /**
     * Connect to the VPN network
     */
open func connect()throws  {try rustCallWithError(FfiConverterTypeCraftNetError.lift) {
    uniffi_craftnet_uniffi_fn_method_craftnetvpn_connect(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Disconnect from the VPN network
     */
open func disconnect()throws  {try rustCallWithError(FfiConverterTypeCraftNetError.lift) {
    uniffi_craftnet_uniffi_fn_method_craftnetvpn_disconnect(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Get available credits
     */
open func getCredits() -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_craftnet_uniffi_fn_method_craftnetvpn_get_credits(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get current privacy level
     */
open func getPrivacyLevel() -> PrivacyLevel {
    return try!  FfiConverterTypePrivacyLevel.lift(try! rustCall() {
    uniffi_craftnet_uniffi_fn_method_craftnetvpn_get_privacy_level(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get current connection state
     */
open func getState() -> ConnectionState {
    return try!  FfiConverterTypeConnectionState.lift(try! rustCall() {
    uniffi_craftnet_uniffi_fn_method_craftnetvpn_get_state(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get network statistics
     */
open func getStats() -> NetworkStats {
    return try!  FfiConverterTypeNetworkStats.lift(try! rustCall() {
    uniffi_craftnet_uniffi_fn_method_craftnetvpn_get_stats(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get current VPN status
     */
open func getStatus() -> VpnStatus {
    return try!  FfiConverterTypeVpnStatus.lift(try! rustCall() {
    uniffi_craftnet_uniffi_fn_method_craftnetvpn_get_status(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Check if connected
     */
open func isConnected() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_craftnet_uniffi_fn_method_craftnetvpn_is_connected(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Set available credits (for testing without payment)
     */
open func setCredits(credits: UInt64) {try! rustCall() {
    uniffi_craftnet_uniffi_fn_method_craftnetvpn_set_credits(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(credits),$0
    )
}
}
    
    /**
     * Set privacy level
     */
open func setPrivacyLevel(level: PrivacyLevel) {try! rustCall() {
    uniffi_craftnet_uniffi_fn_method_craftnetvpn_set_privacy_level(self.uniffiClonePointer(),
        FfiConverterTypePrivacyLevel.lower(level),$0
    )
}
}
    
    /**
     * Process a packet through the tunnel (for Network Extension)
     *
     * This takes raw IP packet data, tunnels it through the VPN,
     * and returns the response packet data.
     */
open func tunnelPacket(packet: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCraftNetError.lift) {
    uniffi_craftnet_uniffi_fn_method_craftnetvpn_tunnel_packet(self.uniffiClonePointer(),
        FfiConverterData.lower(packet),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCraftNetVpn: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = CraftNetVpn

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> CraftNetVpn {
        return CraftNetVpn(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: CraftNetVpn) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CraftNetVpn {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: CraftNetVpn, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCraftNetVpn_lift(_ pointer: UnsafeMutableRawPointer) throws -> CraftNetVpn {
    return try FfiConverterTypeCraftNetVpn.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCraftNetVpn_lower(_ value: CraftNetVpn) -> UnsafeMutableRawPointer {
    return FfiConverterTypeCraftNetVpn.lower(value)
}


/**
 * Network statistics
 */
public struct NetworkStats {
    public var bytesSent: UInt64
    public var bytesReceived: UInt64
    public var requestsMade: UInt64
    public var requestsCompleted: UInt64
    public var uptimeSecs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bytesSent: UInt64, bytesReceived: UInt64, requestsMade: UInt64, requestsCompleted: UInt64, uptimeSecs: UInt64) {
        self.bytesSent = bytesSent
        self.bytesReceived = bytesReceived
        self.requestsMade = requestsMade
        self.requestsCompleted = requestsCompleted
        self.uptimeSecs = uptimeSecs
    }
}



extension NetworkStats: Equatable, Hashable {
    public static func ==(lhs: NetworkStats, rhs: NetworkStats) -> Bool {
        if lhs.bytesSent != rhs.bytesSent {
            return false
        }
        if lhs.bytesReceived != rhs.bytesReceived {
            return false
        }
        if lhs.requestsMade != rhs.requestsMade {
            return false
        }
        if lhs.requestsCompleted != rhs.requestsCompleted {
            return false
        }
        if lhs.uptimeSecs != rhs.uptimeSecs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(bytesSent)
        hasher.combine(bytesReceived)
        hasher.combine(requestsMade)
        hasher.combine(requestsCompleted)
        hasher.combine(uptimeSecs)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNetworkStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NetworkStats {
        return
            try NetworkStats(
                bytesSent: FfiConverterUInt64.read(from: &buf), 
                bytesReceived: FfiConverterUInt64.read(from: &buf), 
                requestsMade: FfiConverterUInt64.read(from: &buf), 
                requestsCompleted: FfiConverterUInt64.read(from: &buf), 
                uptimeSecs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: NetworkStats, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.bytesSent, into: &buf)
        FfiConverterUInt64.write(value.bytesReceived, into: &buf)
        FfiConverterUInt64.write(value.requestsMade, into: &buf)
        FfiConverterUInt64.write(value.requestsCompleted, into: &buf)
        FfiConverterUInt64.write(value.uptimeSecs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetworkStats_lift(_ buf: RustBuffer) throws -> NetworkStats {
    return try FfiConverterTypeNetworkStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetworkStats_lower(_ value: NetworkStats) -> RustBuffer {
    return FfiConverterTypeNetworkStats.lower(value)
}


/**
 * Configuration for the VPN client
 */
public struct VpnConfig {
    public var privacyLevel: PrivacyLevel
    public var bootstrapPeer: String?
    public var requestTimeoutSecs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(privacyLevel: PrivacyLevel, bootstrapPeer: String?, requestTimeoutSecs: UInt64) {
        self.privacyLevel = privacyLevel
        self.bootstrapPeer = bootstrapPeer
        self.requestTimeoutSecs = requestTimeoutSecs
    }
}



extension VpnConfig: Equatable, Hashable {
    public static func ==(lhs: VpnConfig, rhs: VpnConfig) -> Bool {
        if lhs.privacyLevel != rhs.privacyLevel {
            return false
        }
        if lhs.bootstrapPeer != rhs.bootstrapPeer {
            return false
        }
        if lhs.requestTimeoutSecs != rhs.requestTimeoutSecs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(privacyLevel)
        hasher.combine(bootstrapPeer)
        hasher.combine(requestTimeoutSecs)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVpnConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VpnConfig {
        return
            try VpnConfig(
                privacyLevel: FfiConverterTypePrivacyLevel.read(from: &buf), 
                bootstrapPeer: FfiConverterOptionString.read(from: &buf), 
                requestTimeoutSecs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: VpnConfig, into buf: inout [UInt8]) {
        FfiConverterTypePrivacyLevel.write(value.privacyLevel, into: &buf)
        FfiConverterOptionString.write(value.bootstrapPeer, into: &buf)
        FfiConverterUInt64.write(value.requestTimeoutSecs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVpnConfig_lift(_ buf: RustBuffer) throws -> VpnConfig {
    return try FfiConverterTypeVpnConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVpnConfig_lower(_ value: VpnConfig) -> RustBuffer {
    return FfiConverterTypeVpnConfig.lower(value)
}


/**
 * VPN status information
 */
public struct VpnStatus {
    public var state: ConnectionState
    public var peerId: String
    public var connectedPeers: UInt32
    public var credits: UInt64
    public var exitNode: String?
    public var errorMessage: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(state: ConnectionState, peerId: String, connectedPeers: UInt32, credits: UInt64, exitNode: String?, errorMessage: String?) {
        self.state = state
        self.peerId = peerId
        self.connectedPeers = connectedPeers
        self.credits = credits
        self.exitNode = exitNode
        self.errorMessage = errorMessage
    }
}



extension VpnStatus: Equatable, Hashable {
    public static func ==(lhs: VpnStatus, rhs: VpnStatus) -> Bool {
        if lhs.state != rhs.state {
            return false
        }
        if lhs.peerId != rhs.peerId {
            return false
        }
        if lhs.connectedPeers != rhs.connectedPeers {
            return false
        }
        if lhs.credits != rhs.credits {
            return false
        }
        if lhs.exitNode != rhs.exitNode {
            return false
        }
        if lhs.errorMessage != rhs.errorMessage {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(state)
        hasher.combine(peerId)
        hasher.combine(connectedPeers)
        hasher.combine(credits)
        hasher.combine(exitNode)
        hasher.combine(errorMessage)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVpnStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VpnStatus {
        return
            try VpnStatus(
                state: FfiConverterTypeConnectionState.read(from: &buf), 
                peerId: FfiConverterString.read(from: &buf), 
                connectedPeers: FfiConverterUInt32.read(from: &buf), 
                credits: FfiConverterUInt64.read(from: &buf), 
                exitNode: FfiConverterOptionString.read(from: &buf), 
                errorMessage: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: VpnStatus, into buf: inout [UInt8]) {
        FfiConverterTypeConnectionState.write(value.state, into: &buf)
        FfiConverterString.write(value.peerId, into: &buf)
        FfiConverterUInt32.write(value.connectedPeers, into: &buf)
        FfiConverterUInt64.write(value.credits, into: &buf)
        FfiConverterOptionString.write(value.exitNode, into: &buf)
        FfiConverterOptionString.write(value.errorMessage, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVpnStatus_lift(_ buf: RustBuffer) throws -> VpnStatus {
    return try FfiConverterTypeVpnStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVpnStatus_lower(_ value: VpnStatus) -> RustBuffer {
    return FfiConverterTypeVpnStatus.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * VPN connection state
 */

public enum ConnectionState {
    
    case disconnected
    case connecting
    case connected
    case disconnecting
    case error
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionState: FfiConverterRustBuffer {
    typealias SwiftType = ConnectionState

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionState {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .disconnected
        
        case 2: return .connecting
        
        case 3: return .connected
        
        case 4: return .disconnecting
        
        case 5: return .error
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ConnectionState, into buf: inout [UInt8]) {
        switch value {
        
        
        case .disconnected:
            writeInt(&buf, Int32(1))
        
        
        case .connecting:
            writeInt(&buf, Int32(2))
        
        
        case .connected:
            writeInt(&buf, Int32(3))
        
        
        case .disconnecting:
            writeInt(&buf, Int32(4))
        
        
        case .error:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionState_lift(_ buf: RustBuffer) throws -> ConnectionState {
    return try FfiConverterTypeConnectionState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionState_lower(_ value: ConnectionState) -> RustBuffer {
    return FfiConverterTypeConnectionState.lower(value)
}



extension ConnectionState: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Privacy level (number of relay hops)
 */

public enum PrivacyLevel {
    
    case direct
    case light
    case standard
    case paranoid
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePrivacyLevel: FfiConverterRustBuffer {
    typealias SwiftType = PrivacyLevel

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrivacyLevel {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .direct
        
        case 2: return .light
        
        case 3: return .standard
        
        case 4: return .paranoid
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PrivacyLevel, into buf: inout [UInt8]) {
        switch value {
        
        
        case .direct:
            writeInt(&buf, Int32(1))
        
        
        case .light:
            writeInt(&buf, Int32(2))
        
        
        case .standard:
            writeInt(&buf, Int32(3))
        
        
        case .paranoid:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivacyLevel_lift(_ buf: RustBuffer) throws -> PrivacyLevel {
    return try FfiConverterTypePrivacyLevel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePrivacyLevel_lower(_ value: PrivacyLevel) -> RustBuffer {
    return FfiConverterTypePrivacyLevel.lower(value)
}



extension PrivacyLevel: Equatable, Hashable {}




/**
 * Error types for VPN operations
 */
public enum CraftNetError {

    
    
    case NotInitialized
    case AlreadyConnected
    case NotConnected
    case ConnectionFailed(msg: String
    )
    case NoExitNodes
    case Timeout
    case InsufficientCredits
    case InvalidConfig(msg: String
    )
    case InternalError(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCraftNetError: FfiConverterRustBuffer {
    typealias SwiftType = CraftNetError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CraftNetError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NotInitialized
        case 2: return .AlreadyConnected
        case 3: return .NotConnected
        case 4: return .ConnectionFailed(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 5: return .NoExitNodes
        case 6: return .Timeout
        case 7: return .InsufficientCredits
        case 8: return .InvalidConfig(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 9: return .InternalError(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CraftNetError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .NotInitialized:
            writeInt(&buf, Int32(1))
        
        
        case .AlreadyConnected:
            writeInt(&buf, Int32(2))
        
        
        case .NotConnected:
            writeInt(&buf, Int32(3))
        
        
        case let .ConnectionFailed(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        
        case .NoExitNodes:
            writeInt(&buf, Int32(5))
        
        
        case .Timeout:
            writeInt(&buf, Int32(6))
        
        
        case .InsufficientCredits:
            writeInt(&buf, Int32(7))
        
        
        case let .InvalidConfig(msg):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InternalError(msg):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


extension CraftNetError: Equatable, Hashable {}

extension CraftNetError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
/**
 * Create a VPN configuration with custom settings
 */
public func createConfig(privacyLevel: PrivacyLevel, bootstrapPeer: String?, requestTimeoutSecs: UInt64) -> VpnConfig {
    return try!  FfiConverterTypeVpnConfig.lift(try! rustCall() {
    uniffi_craftnet_uniffi_fn_func_create_config(
        FfiConverterTypePrivacyLevel.lower(privacyLevel),
        FfiConverterOptionString.lower(bootstrapPeer),
        FfiConverterUInt64.lower(requestTimeoutSecs),$0
    )
})
}
/**
 * Create a default VPN configuration
 */
public func createDefaultConfig() -> VpnConfig {
    return try!  FfiConverterTypeVpnConfig.lift(try! rustCall() {
    uniffi_craftnet_uniffi_fn_func_create_default_config($0
    )
})
}
/**
 * Initialize the library (call once at app startup)
 */
public func initLibrary() {try! rustCall() {
    uniffi_craftnet_uniffi_fn_func_init_library($0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_craftnet_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_func_create_config() != 7608) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_func_create_default_config() != 17790) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_func_init_library() != 50454) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_method_craftnetvpn_connect() != 40542) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_method_craftnetvpn_disconnect() != 47424) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_method_craftnetvpn_get_credits() != 24719) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_method_craftnetvpn_get_privacy_level() != 17898) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_method_craftnetvpn_get_state() != 301) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_method_craftnetvpn_get_stats() != 22431) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_method_craftnetvpn_get_status() != 57413) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_method_craftnetvpn_is_connected() != 22520) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_method_craftnetvpn_set_credits() != 62554) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_method_craftnetvpn_set_privacy_level() != 23283) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_method_craftnetvpn_tunnel_packet() != 63531) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_craftnet_uniffi_checksum_constructor_craftnetvpn_new() != 34546) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all